### ISSUE TITLE
お支払い手続き選択画面に表示されるコンビニ一覧から「サークルKサンクス」を選択できなくしたい

### ISSUE THREAD

**Issue by ko31** [tarosky/kuroneko-pay#11]
全国のサークルＫサンクス店舗がファミリーマートへの転換するのに伴い、
お支払い手続き選択画面に表示されるコンビニ一覧から「サークルKサンクス」を選択ができなくなるよう変更する。

**Comment by fumikito** [comment]
プルリクマージしました。リリースには次の作業を行なってください。

readmeのバージョンを上げ、Changelogに変更内容を記載する。
ブートストラップファイル[]()のバージョンをあげる

蒸気

**Comment by ko31** [comment]
リリース完了につきクローズします。
