### ISSUE TITLE
公式リポジトリのヘッダー画像と、アイコンを設置する

### ISSUE THREAD

**Issue by atsufumiyoshikawa** [tarosky/kuroneko-pay#3]
- ヘッダー画像
-- ![banner-2](https://user-images.githubusercontent.com/8207033/43704128-b0a0a76c-9999-11e8-8abf-9c6ed6ca9f12.png)

- アイコン
-- ![profile-thumb](https://user-images.githubusercontent.com/8207033/43704129-b0e81610-9999-11e8-839e-e2464fae0cb4.png)

**Comment by fumikito** [comment]
@atsufumiyoshikawa ヘッダーだけ反映済みです。ロゴ画像がサイズ小さいので、256x256待ちです。
